"""
`cslcore limits`: what each agent may do, in your own numbers, and the policy made from it.

    cslcore limits                                   every agent: its limits in one line, guarded or not
    cslcore limits --agent payments                  one agent, tool by tool
    cslcore limits --agent payments --set refund_order=100k..300k
    cslcore limits --agent payments --decide delete_customer=block
    cslcore limits --agent payments --add-tool wire_transfer:spend:amount
    cslcore limits --agent payments --profile strict
    cslcore limits --check                           sample calls decided by the active policies

A change makes the policy again from the limits, checks it (parse, validate, Z3), shows the diff,
and after confirmation activates it and its mapping, then decides sample calls with it (what runs,
what stops) against the limits. Guards that are running pick it up on their
next call. Policies written by hand (in the studio or an editor) are not overwritten: their limits
are edited there.
"""

from __future__ import annotations

from typing import List

from rich.table import Table
from rich.text import Text

from .commands import EXIT_CHECK_FAILED, EXIT_OK, EXIT_USAGE, console_for, workspace_for
from .policy import limits as L

MADE_FROM_LIMITS = "made from its limits"


def scope_for(ws, args, agent) -> List[str]:
    from .wire_cmd import scan_probe

    probe, _root = scan_probe(args, ws)
    base = agent.project or (probe.home() if agent.kind == "assistant" else None)
    return [probe.real_path(base)] if base else []


def limits_of(ws, args, agent) -> L.Limits:
    from .policy.draft import agent_key

    return L.defaults(agent, scope_for(ws, args, agent), L.load(ws, agent_key(agent)))


def status_of(ws, agent) -> Text:
    from .controls import Controls
    from .policy.draft import agent_key

    key = agent_key(agent)
    if agent.guard.status == "none":
        return Text("not wired", style="warn")
    ctl = Controls(ws).get(key)
    if ctl.disabled:
        return Text("frozen", style="high")
    return Text("block", style="ok") if ctl.mode == "block" else Text("log: recorded, not stopped", style="warn")


def show_agent(console, ws, agent, lim: L.Limits) -> None:
    t = Table(box=None, show_header=True, header_style="label", pad_edge=False, padding=(0, 2, 0, 0))
    t.add_column("TOOL", style="head", no_wrap=True)
    t.add_column("KIND", style="label", no_wrap=True)
    t.add_column("WHAT HAPPENS")
    for name, kind, what in L.describe(lim):
        t.add_row(name, kind, Text(what, style="text"))
    console.print(Text.assemble(("  ", ""), (agent.display_name, "head"), (f"   {lim.profile} profile · ", "muted"),
                                status_of(ws, agent)))
    if lim.scope:
        console.print(Text.assemble(("  writes under  ", "muted"), (", ".join(lim.scope), "text")))
    console.print(t)


def apply_limits(console, ws, args, agent, lim: L.Limits, yes: bool) -> bool:
    """Make the policy from the limits, check it, show the diff, and on confirmation activate it."""
    from .policy.binder import bind
    from .policy.draft import agent_key
    from .policy.gate import verify_text
    from .policy.workbench import confirm, diff_text

    key = agent_key(agent)
    path = ws.policies / f"{key}.csl"
    old = ws.read(path)
    if old and MADE_FROM_LIMITS not in old and "Generated by CSL-Core Venom" not in old:
        console.print(f"  [warn]{ws.rel(path)} was written by hand; its limits are edited there "
                      f"(cslcore studio --agent {key})[/warn]")
        return False
    text, _notes = L.policy_text(agent, lim)
    gate = verify_text(text)
    if not gate.ok:
        issue = gate.issues[0].message if gate.issues else gate.stage
        console.print(f"  [high]the policy for these limits does not pass the check: {issue}[/high]")
        return False
    if old == text:
        L.save(ws, lim)
        console.print("  [muted]the policy already says this[/muted]")
        return True
    if old:
        d = diff_text(old, text, ws.rel(path), "new")
        if d:
            console.print(d)
    if not confirm(console, f"Activate the new limits for {key}?", yes, default=True):
        console.print("  [muted]nothing changed[/muted]")
        return False
    if ws.plan_only:
        console.print(f"  [muted]--plan-only: would write {ws.rel(path)}[/muted]")
        return False
    L.save(ws, lim)
    ws.write_text(path, text)
    if not old:
        from .controls import mode_on_activation
        mode_on_activation(ws, key, True)
    plan = bind(ws, path, [agent])
    res = plan.results[0] if plan.results else None
    if res is None or not res.ok:
        console.print(f"  [high]the mapping did not pass its test: {res.message if res else 'no result'}; "
                      "the previous mapping is kept[/high]")
        return False
    console.print(Text.assemble(("  ✓ active ", "ok"), (ws.rel(path), "head"),
                                ("  running guards use it from their next call", "muted")))
    return True


def cmd_limits(args) -> int:
    from .policy.draft import agent_key
    from .watch import _inventory

    console = console_for(args)
    ws = workspace_for(args)
    inv = _inventory(ws)
    if inv is None:
        console.print("  [warn]no scan in this workspace yet: run cslcore venom (or cslcore setup) first[/warn]")
        return EXIT_USAGE
    want = getattr(args, "agent", None)
    checking = bool(getattr(args, "check", False))
    if not want:
        failed = 0
        for a in inv.agents:
            if a.tools:
                if checking:
                    failed += not show_check(console, ws, a)
                else:
                    show_agent(console, ws, a, limits_of(ws, args, a))
                console.print()
        if not checking:
            console.print(Text("  change one: cslcore limits --agent NAME --set TOOL=FREE..MAX   "
                               "check them: cslcore limits --check", style="muted"))
        return EXIT_CHECK_FAILED if failed else EXIT_OK
    agent = next((a for a in inv.agents if want in (agent_key(a), a.display_name, a.id)), None)
    if agent is None:
        console.print(f"[high]no agent matches '{want}'[/high]")
        return EXIT_USAGE
    key = agent_key(agent)
    lim = limits_of(ws, args, agent)
    changed = False
    try:
        sets = [f"{key}.{s}" for s in getattr(args, "set", None) or []]
        adds = [f"{key}:{s}" for s in getattr(args, "add_tool", None) or []]
        done = L.apply_flags(lim, key, (), adds, getattr(args, "profile", None))
        lim = L.defaults(agent, lim.scope, lim)  # added tools get their kind before their numbers are set
        done += L.apply_flags(lim, key, sets, (), None)
        for spec in getattr(args, "decide", None) or []:
            tool, _, how = spec.partition("=")
            if how not in ("allow", "approval", "block", "standard"):
                raise L.LimitError(f"--decide wants TOOL=allow|approval|block|standard, got {spec!r}")
            if tool not in lim.tools:
                raise L.LimitError(f"{key} has no tool {tool!r}")
            lim.tools[tool].decide = None if how == "standard" else how
            done.append(f"{tool}: {how}")
        for folder in getattr(args, "scope", None) or []:
            if folder not in lim.scope:
                lim.scope.append(folder)
                done.append(f"may write under {folder}")
    except L.LimitError as e:
        console.print(f"  [high]{e}[/high]")
        return EXIT_USAGE
    changed = bool(done)
    if changed:
        repo_file_note(console, key)
    for item in done:
        console.print(Text.assemble(("  · ", "muted"), (item, "text")))
    if changed:
        console.print()
        if not apply_limits(console, ws, args, agent, lim, bool(getattr(args, "yes", False))):
            return EXIT_OK
        console.print()
    if not checking:
        show_agent(console, ws, agent, lim)
    if changed or checking:
        if changed:
            console.print()
        return EXIT_OK if show_check(console, ws, agent, lim) else EXIT_CHECK_FAILED
    return EXIT_OK


def repo_file_note(console, key: str) -> None:
    """A repository that keeps this agent's limits in csl-limits.ini: the file is where they change."""
    from .apply_cmd import FILE, LimitsFileError, find_file, parse

    path = find_file()
    try:
        named = path is not None and key in parse(path.read_text(encoding="utf-8"))
    except (LimitsFileError, OSError):
        named = False
    if named:
        console.print(Text(f"  {key}'s limits are kept in {path}; this change lasts until the next cslcore apply. "
                           f"To keep it, change {FILE} (and review it in a pull request).", style="warn"))


def show_check(console, ws, agent, lim=None, compact: bool = False) -> bool:
    """The check table for one agent; False when a sample call is not decided as its limits say."""
    from . import check
    from .board import store_check
    from .policy.draft import agent_key

    report = check.run(ws, agent, lim)
    if report.cases and not ws.plan_only:
        store_check(ws, agent_key(agent), report)
    from .board import approval_note

    check.show(console, report, agent.display_name, compact=compact, approval=approval_note(None, ws, agent))
    return report.ok or not report.cases
