"""Generate policies/<agent>_mapping.py from a MappingSpec (fail-closed helpers only)."""

from __future__ import annotations

import json
from typing import List

from .. import VENOM_VERSION
from ..analysis.coverage import suggest
from .spec import COMMAND_PARAMS, DESTINATION_PARAMS, NEUTRAL, PATH_PARAMS, MappingSpec, VarSpec, pick_param


DERIVED_NOTE = {"command_class": "what the command would do", "sql_class": "what the query would do",
                "path_class": "where the call writes or reads, against SCOPE_ROOTS"}


def q(v) -> str:
    """Python literal with double quotes (json is valid Python for str / list / dict of str)."""
    return json.dumps(v, ensure_ascii=False)


def _neutral(v: VarSpec) -> str:
    if v.kind == "range":
        return repr(v.low if v.low is not None else 0)
    if v.kind == "flag":
        return '"NO"'
    if v.kind == "enum" and v.values:
        return q(v.values[0])
    return "None"


def _helper(v: VarSpec, expr: str, ptype: str = "", penum=None) -> str:
    if v.kind == "range":
        if (ptype or "").lower().split("[")[0] in ("list", "array", "tuple", "set", "sequence"):
            expr = f"count_of({expr})"  # a list parameter: its length is what the limit counts
        return f'to_range({expr}, {v.low}, {v.high}, name="{v.name}")'
    if v.kind == "flag":
        return f'to_flag({expr}, name="{v.name}")'
    if v.kind == "enum":
        if penum:
            table = {raw: (raw if raw in v.values else suggest(raw, v.values)) for raw in penum}
            table = {k: x for k, x in table.items() if x}
            return f'to_enum({expr}, {q(table)}, name="{v.name}")'
        return f'to_enum({expr}, {q(v.values)}, name="{v.name}")'
    return f'{expr}  # TODO: domain not supported by the generator; map explicitly'


def generate(spec: MappingSpec, policy_rel: str) -> str:
    out: List[str] = [
        '"""',
        f"Mapping for {spec.agent_name} ({spec.agent_id}) onto {policy_rel}.",
        "",
        f"Generated by CSL-Core Venom {VENOM_VERSION}. Every value that cannot be mapped raises",
        "MappingError, which the integration treats as a block (chimera_core.mapping.guarded_verify).",
        f"Test it with: cslcore map --agent {spec.agent_name} --test",
        '"""',
        "",
        "from chimera_core.actions import args_command_class, args_path_class, args_sql_class, count_of",
        "from chimera_core.mapping import (MappingError, command_allowed, destination_allowed, in_scope, to_enum,",
        "                                  to_flag, to_range)",
        "",
        f"POLICY = {q(policy_rel)}",
        f"AGENT_ID = {q(next((v.constant for v in spec.variables if v.source == 'constant'), spec.agent_key))}",
        "",
        "# real tool name -> policy value (tools not listed here are blocked)",
        "TOOLS = {",
    ]
    for real, pol in spec.tool_table.items():
        out.append(f"    {q(real)}: {q(pol)},")
    out.append("}")
    if spec.unmapped_tools:
        out.append(f"# not in the policy vocabulary, blocked until added: {', '.join(spec.unmapped_tools)}")
    derived = {v.name for v in spec.variables if v.source == "derived"}
    if derived & {"command_allowlisted", "destination_allowlisted", "target_in_scope", "command_class", "path_class"}:
        out += ["", f"# From the agent's limits (cslcore limits --agent {spec.agent_key}); an empty allowlist allows nothing."]
    if "command_allowlisted" in derived:
        out.append(f"COMMAND_ALLOWLIST = {q(spec.commands)}  # exact commands; \"git log *\" also takes plain arguments")
    if "destination_allowlisted" in derived:
        out.append(f"DESTINATION_ALLOWLIST = {q(spec.destinations)}  # hosts (\"api.example.com\", \"*.example.com\"), addresses")
    if derived & {"target_in_scope", "command_class", "path_class"}:
        out.append(f"SCOPE_ROOTS = {q(spec.scope_roots)}  # the folders the agent may write under")
    out += ["", "", "def map_call(tool_name, args, context=None):",
            '    """Return the policy variables for one tool call; raises MappingError when a value cannot be mapped."""',
            "    args = args or {}", "    context = context or {}",
            "    if not isinstance(args, dict):", '        raise MappingError("args", args, "expected a dict")']
    tv = spec.tool_var
    out.append(f'    ctx = {{{q(tv)}: to_enum(tool_name, TOOLS, name={q(tv)})}}' if tv else "    ctx = {}")
    for v in spec.variables:
        if v.source == "tool":
            continue
        out.append("")
        dom = f"{v.low}..{v.high}" if v.kind == "range" else ("{" + ", ".join(v.values) + "}" if v.values else v.kind)
        if v.source == "constant":
            out.append(f"    ctx[{q(v.name)}] = AGENT_ID")
        elif v.source == "param":
            srcs = ", ".join(f"{t}.{p.name}" for t, p in v.params.items())
            out.append(f"    # {v.name}: {dom}, from {srcs}")
            first = True
            for tname, p in v.params.items():
                kw = "if" if first else "elif"
                first = False
                out.append(f"    {kw} tool_name == {q(tname)}:")
                out.append(f"        ctx[{q(v.name)}] = {_helper(v, f'args.get({q(p.name)})', p.type or '', p.enum)}")
            out.append("    else:")
            out.append(f"        ctx[{q(v.name)}] = {_neutral(v)}  # not supplied by this tool: neutral value")
        elif v.name in NEUTRAL:
            wanted = set(spec.derived_tools.get(v.name, []))
            real = [r for r, pol in spec.tool_table.items() if pol in wanted]
            call = {"command_class": "args_command_class(args, SCOPE_ROOTS)", "sql_class": "args_sql_class(args)",
                    "path_class": "args_path_class(args, SCOPE_ROOTS)"}[v.name]
            out.append(f"    # {v.name}: {DERIVED_NOTE.get(v.name, '')}")
            if real:
                out.append(f"    if tool_name in {q(sorted(real))}:")
                out.append(f"        ctx[{q(v.name)}] = {call}")
                out.append("    else:")
                out.append(f"        ctx[{q(v.name)}] = {q(NEUTRAL[v.name])}  # no rule of this tool speaks about it")
            else:
                out.append(f"    ctx[{q(v.name)}] = {q(NEUTRAL[v.name])}")
        elif v.name == "approval":
            out.append("    # approval: supplied by the caller; missing means NO")
            out.append('    ctx["approval"] = to_flag(context.get("approval"), name="approval", required=False, default="NO")')
        elif v.name in ("command_allowlisted", "destination_allowlisted", "target_in_scope"):
            rx, helper = {"command_allowlisted": (COMMAND_PARAMS, "command_allowed({}, COMMAND_ALLOWLIST)"),
                          "destination_allowlisted": (DESTINATION_PARAMS, "destination_allowed({}, DESTINATION_ALLOWLIST)"),
                          "target_in_scope": (PATH_PARAMS, "in_scope({}, SCOPE_ROOTS)")}[v.name]
            out.append(f"    # {v.name}: {spec.var(v.name).note if spec.var(v.name) else ''}")
            branches = []
            for tname, params in spec.tool_params.items():
                pname = pick_param(params, rx)
                if pname and tname in spec.tool_table:
                    branches.append((tname, pname))
            for i, (tname, pname) in enumerate(branches):
                kw = "if" if i == 0 else "elif"
                out.append(f"    {kw} tool_name == {q(tname)}:")
                out.append(f"        ctx[{q(v.name)}] = {helper.format(f'args.get({q(pname)})')}")
            if branches:
                out.append("    else:")
                out.append(f'        ctx[{q(v.name)}] = "NO"')
            else:
                out.append(f'    ctx[{q(v.name)}] = "NO"')
        else:
            out.append(f"    # {v.name}: {dom}, supplied by the caller in context")
            out.append(f"    ctx[{q(v.name)}] = {_helper(v, f'context.get({q(v.name)})')}")
    out += ["", "    return ctx", ""]
    return "\n".join(out)
